server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        ddl-auto: create
  #   generate-ddl: true
  # datasource:
  #   url: jdbc:sqlserver://localhost:1433;databaseName=CustomerCenter
  #   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #   username: SA
  #   password: My@strongpassword
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: CustomerCenter
          destination: taxi
          contentType: application/json
        event-out:
          destination: taxi
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8084
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: CustomerCenter
          destination: taxi
          contentType: application/json
        event-out:
          destination: taxi
          contentType: application/json